### ISSUE TITLE
Wins/Losses by Group Member Trend Graph Off-by-One

### ISSUE THREAD

**Issue by pseudobeard** [cheshire137/competiwatch#31]
When looking at https://competiwatch.herokuapp.com/trends/9/ATastySnack-1553, I noticed that the wins/losses by group member graph was off by one.  It is showing each bar as 1 less than the actual value.

**Comment by pseudobeard** [comment]
`<canvas class="js-win-loss-bar-chart chartjs-render-monitor" data-labels="[&quot;Jamie&quot;,&quot;Rob&quot;,&quot;Siege&quot;,&quot;Zion&quot;]" data-wins="[4,5,5,7]" data-losses="[2,1,1,2]" data-draws="[1,1,1,1]" width="487" height="300" style="display: block; width: 487px; height: 300px;"></canvas>`

Relevant source.  Looks like because there are no elements with "0", the graph axis scales from min to max.  Probably need to force the axis to start at 0 here.

**Comment by cheshire137** [comment]
Thanks for the report! I'm going to temporarily make your ATastySnack season 9 publicly visible so I can see the graph.

**Comment by cheshire137** [comment]
Here's the chart in question:

<img width="1017" alt="atastysnack_1553___season_9___trends_-_competiwatch" src="https://user-images.githubusercontent.com/82317/36938992-98b2c0d8-1eef-11e8-9c4c-d9d4ca300f8a.png">

**Comment by cheshire137** [comment]
I deployed a fix. Turns out Chart.js, the charting library I'm using, has an option to force an axis scale to start at 0, so I used that. Here's the chart now:

<img width="1011" alt="atastysnack_1553___season_9___trends_-_competiwatch" src="https://user-images.githubusercontent.com/82317/36939162-2a7cc3d6-1ef2-11e8-8725-d4dbe72022f9.png">

**Comment by pseudobeard** [comment]
Looks much better!  Thanks!
