### ISSUE TITLE
Competiwatch Logo?

### ISSUE THREAD

**Issue by connorshea** [cheshire137/competiwatch#99]
@cheshire137 I won't claim to be an amazing graphic designer or anything, but if you have any logo ideas you want to pitch I can try my hand at them :) If not that's fine too, just want to be helpful if I can ^_^

Proof I'm not completely incompetent with design 😛: 

- https://www.behance.net/gallery/18931105/Steam-Redesign-Concept
- [the logo for FNA](http://fna-xna.github.io/)

I imagine a variation of the Overwatch logo wouldn't really be kosher, not too sure what else to base it off.

**Comment by cheshire137** [comment]
Oh no, I just saw this now when you closed it! I'm sorry for the delay.

If you'd like to create a logo for Competiwatch, I'd love your help! 💖 

> I imagine a variation of the Overwatch logo wouldn't really be kosher

Yeah, I think so, too. I'm not sure what would be acceptable. Could a hero outline be used? Definitely using Tracer probably wouldn't work since they use Tracer outlines in a lot of official branding, so maybe it wouldn't be good to use other heroes either.
